//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34209
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Resources;
using System.Diagnostics;
using System.Globalization;
using System.ComponentModel;
using System.CodeDom.Compiler;
using System.Runtime.CompilerServices;
using System.Diagnostics.CodeAnalysis;

namespace AutoRun.Properties
{
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.

    [CompilerGeneratedAttribute()]
    [DebuggerNonUserCodeAttribute()]
    [GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    internal sealed partial class Resources : Object
    {
        private static CultureInfo resourceCulture;
        private static ResourceManager instance;

        /// <summary>
        ///   Конструктор типа класса.
        /// </summary>
        [SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        static Resources()
        {
            Resources.instance = new ResourceManager("AutoRun.Properties.Resources", typeof(Resources).Assembly);

            return;
        }

        /// <summary>
        ///   Конструктор экземпляра класса.
        /// </summary>
        [SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        private Resources()
        {
            return;
        }

        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [EditorBrowsableAttribute(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager
        {
            get
            {
                return Resources.instance;
            }
        }

        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [EditorBrowsableAttribute(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture
        {   
            get
            {
                return ((CultureInfo)(Resources.resourceCulture));
            }
            set
            {
                Resources.resourceCulture = ((CultureInfo)(value));
            }
        }
    }
}
