//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.1
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Diagnostics;
using System.Configuration;
using System.CodeDom.Compiler;
using System.Runtime.CompilerServices;

namespace AutoRun.Properties
{
    [CompilerGeneratedAttribute()]
    [GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : ApplicationSettingsBase
    {
        private static Settings instance;

        static Settings()
        {
            Settings.instance = new Settings();

            return;
        }

        private Settings()
        {
            return;
        }

        public static Settings Default
        {
            get
            {
                return Settings.instance;
            }
        }
        
        [UserScopedSettingAttribute()]
        [DebuggerNonUserCodeAttribute()]
        [DefaultSettingValueAttribute("")]
        public String dbLogin
        {
            get
            {
                return this["dbLogin"].ToString();
            }
            set
            {
                this["dbLogin"] = value.ToString();
            }
        }
        
        [UserScopedSettingAttribute()]
        [DebuggerNonUserCodeAttribute()]
        [DefaultSettingValueAttribute("")]
        public String dbPassword
        {
            get
            {
                return this["dbPassword"].ToString();
            }
            set
            {
                this["dbPassword"] = value.ToString();
            }
        }
        
        [UserScopedSettingAttribute()]
        [DebuggerNonUserCodeAttribute()]
        [DefaultSettingValueAttribute("")]
        public String dbHost
        {
            get
            {
                return this["dbHost"].ToString();
            }
            set {
                this["dbHost"] = value.ToString();
            }
        }
        
        [UserScopedSettingAttribute()]
        [DebuggerNonUserCodeAttribute()]
        [DefaultSettingValueAttribute("")]
        public String dbPort
        {
            get
            {
                return this["dbPort"].ToString();
            }
            set
            {
                this["dbPort"] = value.ToString();
            }
        }
        
        [UserScopedSettingAttribute()]
        [DebuggerNonUserCodeAttribute()]
        [DefaultSettingValueAttribute("")]
        public String dbService
        {
            get
            {
                return this["dbService"].ToString();
            }
            set
            {
                this["dbService"] = value.ToString();
            }
        }
        
        [UserScopedSettingAttribute()]
        [DebuggerNonUserCodeAttribute()]
        [DefaultSettingValueAttribute("")]
        public String srvLogin
        {
            get
            {
                return this["srvLogin"].ToString();
            }
            set
            {
                this["srvLogin"] = value.ToString();
            }
        }
        
        [UserScopedSettingAttribute()]
        [DebuggerNonUserCodeAttribute()]
        [DefaultSettingValueAttribute("")]
        public String srvPassword
        {
            get
            {
                return this["srvPassword"].ToString();
            }
            set
            {
                this["srvPassword"] = value.ToString();
            }
        }
        
        [UserScopedSettingAttribute()]
        [DebuggerNonUserCodeAttribute()]
        [DefaultSettingValueAttribute("")]
        public String srvHost
        {
            get
            {
                return this["srvHost"].ToString();
            }
            set
            {
                this["srvHost"] = value.ToString();
            }
        }
        
        [UserScopedSettingAttribute()]
        [DebuggerNonUserCodeAttribute()]
        [DefaultSettingValueAttribute("2212")]
        public String srvPort
        {
            get
            {
                return this["srvPort"].ToString();
            }
            set
            {
                this["srvPort"] = value.ToString();
            }
        }
        
        [UserScopedSettingAttribute()]
        [DebuggerNonUserCodeAttribute()]
        [DefaultSettingValueAttribute("offCash")]
        public String srvService
        {
            get
            {
                return this["srvService"].ToString();
            }
            set
            {
                this["srvService"] = value.ToString();
            }
        }
        
        [UserScopedSettingAttribute()]
        [DebuggerNonUserCodeAttribute()]
        [DefaultSettingValueAttribute("")]
        public String idMega
        {
            get
            {
                return this["idMega"].ToString();
            }
            set
            {
                this["idMega"] = value.ToString();
            }
        }
    }
}
